import { Plugin } from '../../core/lib/types/plugin.types';
import { FileText } from 'lucide-react';

export const reportingExportAdvancedPlugin: Plugin = {
  id: 'reporting-export-advanced',
  name: 'Advanced Reporting & Export',
  description: 'Comprehensive reporting system with scheduled reports, custom templates, multi-format exports, email delivery, and executive dashboards',
  version: '1.0.0',
  category: 'reporting',
  icon: FileText,
  author: 'AuraFlow',
  enabled: true,
  config: {
    scheduledReports: {
      enabled: true,
      allowedFrequencies: ['daily', 'weekly', 'monthly', 'quarterly'],
      deliveryMethods: ['email', 'download', 'api'],
      maxScheduledReports: 20,
      timezone: 'auto', // Use browser timezone
      defaultDeliveryTime: '08:00', // 8 AM
      retentionDays: 90, // Keep report history for 90 days
    },
    exportFormats: {
      pdf: {
        enabled: true,
        includeLogo: true,
        includeCharts: true,
        pageSize: 'letter', // 'letter', 'a4', 'legal'
        orientation: 'portrait', // 'portrait', 'landscape'
      },
      excel: {
        enabled: true,
        includeRawData: true,
        includeCharts: true,
        multipleSheets: true,
        formatting: 'styled', // 'basic', 'styled'
      },
      csv: {
        enabled: true,
        delimiter: ',', // ',', ';', '\t'
        includeHeaders: true,
        encoding: 'utf-8',
      },
      json: {
        enabled: true,
        prettyPrint: true,
        includeMetadata: true,
      },
    },
    reportTemplates: {
      useTemplates: true,
      allowCustomTemplates: true,
      builtInTemplates: [
        'daily-sales-summary',
        'weekly-performance',
        'monthly-financial',
        'inventory-status',
        'employee-performance',
        'customer-insights',
        'executive-summary',
        'tax-report',
        'audit-trail',
      ],
      customFields: true,
      templateSharing: false, // Share templates across users
    },
    emailDelivery: {
      enabled: true,
      maxRecipients: 10,
      includeAttachment: true,
      allowBcc: true,
      customSubject: true,
      customMessage: true,
      retryFailedDeliveries: true,
      maxRetries: 3,
    },
    dashboards: {
      executiveDashboard: true,
      customizableWidgets: true,
      realTimeData: true,
      dateRangeComparison: true,
      exportDashboard: true,
      shareDashboard: false, // Future feature
      refreshInterval: 300, // seconds (5 minutes)
    },
    dataAccess: {
      salesData: true,
      inventoryData: true,
      customerData: true,
      employeeData: true,
      financialData: true,
      analyticsData: true,
      auditData: false, // Requires additional permissions
    },
    customization: {
      allowFilters: true,
      allowGrouping: true,
      allowSorting: true,
      allowCalculations: true,
      allowFormatting: true,
      saveCustomReports: true,
      maxSavedReports: 50,
    },
    security: {
      requireApproval: false, // Require approval before sending
      dataRedaction: false, // Redact sensitive data
      watermark: false, // Add watermark to reports
      accessLog: true, // Log who generates/views reports
      roleBasedAccess: true, // Restrict report types by role
    },
    performance: {
      maxRecords: 100000, // Maximum records per report
      cacheResults: true,
      cacheDuration: 3600, // 1 hour
      asyncGeneration: true, // Generate large reports in background
      compressionEnabled: true,
    },
  },
  requiredPermissions: ['view_reports', 'export_data'],
  dependencies: [],
  optionalDependencies: [
    'analytics-reporting',
    'customer-management-advanced',
    'employee-performance',
    'inventory-management-advanced',
    'multi-location',
  ],
  industries: ['restaurant', 'retail', 'cafe', 'pharmacy', 'salon', 'general', 'ultimate'],
  packageTier: 'professional',
  routes: [
    {
      path: '/admin/reports/advanced',
      component: 'AdvancedReporting',
    },
    {
      path: '/admin/reports/scheduled',
      component: 'ScheduledReports',
    },
    {
      path: '/admin/reports/templates',
      component: 'ReportTemplates',
    },
    {
      path: '/admin/reports/executive',
      component: 'ExecutiveDashboard',
    },
  ],
  adminNavigation: {
    label: 'Advanced Reports',
    icon: FileText,
    path: '/admin/reports/advanced',
    section: 'reports',
    order: 1,
  },
  features: [
    'Scheduled report automation',
    'Daily, weekly, monthly reports',
    'Email delivery to multiple recipients',
    'PDF export with branding',
    'Excel export with charts',
    'CSV export for data analysis',
    'JSON API export',
    'Custom report templates',
    '9 built-in report types',
    'Executive summary dashboard',
    'Real-time dashboard widgets',
    'Date range comparison',
    'Multi-location reporting',
    'Employee performance reports',
    'Inventory status reports',
    'Customer analytics reports',
    'Sales summary reports',
    'Financial reports',
    'Tax reports',
    'Audit trail reports',
    'Custom field mapping',
    'Advanced filtering',
    'Grouping and aggregation',
    'Report scheduling calendar',
    'Report history archive',
    'One-click regeneration',
    'Batch export multiple reports',
    'Report templates library',
    'Custom calculations',
    'Conditional formatting',
    'Data visualization in exports',
    'Role-based report access',
    'Report generation logs',
    'Failed delivery retry',
    'Automatic data refresh',
  ],
  settings: [
    {
      key: 'scheduledReports.enabled',
      label: 'Enable Scheduled Reports',
      type: 'boolean',
      defaultValue: true,
      description: 'Allow automated report generation and delivery',
    },
    {
      key: 'scheduledReports.defaultDeliveryTime',
      label: 'Default Delivery Time',
      type: 'text',
      defaultValue: '08:00',
      description: 'Default time for scheduled report delivery (24h format)',
    },
    {
      key: 'exportFormats.pdf.enabled',
      label: 'Enable PDF Export',
      type: 'boolean',
      defaultValue: true,
      description: 'Allow exporting reports as PDF files',
    },
    {
      key: 'exportFormats.excel.enabled',
      label: 'Enable Excel Export',
      type: 'boolean',
      defaultValue: true,
      description: 'Allow exporting reports as Excel files',
    },
    {
      key: 'exportFormats.csv.enabled',
      label: 'Enable CSV Export',
      type: 'boolean',
      defaultValue: true,
      description: 'Allow exporting reports as CSV files',
    },
    {
      key: 'emailDelivery.enabled',
      label: 'Enable Email Delivery',
      type: 'boolean',
      defaultValue: true,
      description: 'Allow emailing reports to recipients',
    },
    {
      key: 'emailDelivery.maxRecipients',
      label: 'Max Email Recipients',
      type: 'number',
      defaultValue: 10,
      description: 'Maximum number of email recipients per report',
    },
    {
      key: 'dashboards.executiveDashboard',
      label: 'Enable Executive Dashboard',
      type: 'boolean',
      defaultValue: true,
      description: 'Show high-level executive summary dashboard',
    },
    {
      key: 'dashboards.refreshInterval',
      label: 'Dashboard Refresh Interval (seconds)',
      type: 'number',
      defaultValue: 300,
      description: 'How often to refresh real-time data',
    },
    {
      key: 'performance.maxRecords',
      label: 'Max Records Per Report',
      type: 'number',
      defaultValue: 100000,
      description: 'Maximum number of records in a single report',
    },
  ],
  businessBenefits: [
    'Save 10+ hours/week on manual reporting',
    'Automated insights delivered on schedule',
    'Make faster decisions with real-time data',
    'Share reports with stakeholders easily',
    'Comply with financial reporting requirements',
    'Track KPIs across multiple time periods',
    'Identify trends and patterns automatically',
    'Reduce errors from manual data compilation',
    'Access data anywhere (email, mobile)',
    'Support multi-location rollup reporting',
    'Empower managers with self-service reports',
    'Archive historical data for analysis',
    'Export for accounting/tax preparation',
    'Professional branded reports for investors',
    'Data-driven performance reviews',
  ],
  useCases: [
    'Daily sales summary emailed to owner',
    'Weekly performance review for managers',
    'Monthly financial close reports',
    'Quarterly board meeting packages',
    'End-of-day cash reconciliation',
    'Inventory reorder reports',
    'Employee performance reviews',
    'Customer lifetime value analysis',
    'Tax preparation exports',
    'Audit trail documentation',
    'Multi-location comparison reports',
    'Year-over-year trend analysis',
    'Seasonal planning reports',
    'Vendor payment reports',
    'Commission calculation exports',
  ],
  metrics: {
    reportGeneration: 'Number of reports generated',
    scheduledDeliveries: 'Automated reports delivered',
    exportVolume: 'Total exports by format',
    emailSuccess: 'Email delivery success rate',
    averageGenerationTime: 'Avg time to generate report',
    mostPopularReports: 'Most frequently run reports',
    dataExported: 'Total data volume exported',
    scheduledReportCount: 'Active scheduled reports',
    templateUsage: 'Template usage statistics',
    executiveDashboardViews: 'Dashboard view count',
  },
  dataSchema: {
    scheduledReport: {
      id: 'string',
      name: 'string',
      templateId: 'string',
      frequency: 'daily | weekly | monthly | quarterly',
      deliveryTime: 'string',
      recipients: 'string[]',
      format: 'pdf | excel | csv | json',
      filters: 'object',
      nextRun: 'Date',
      lastRun: 'Date | null',
      enabled: 'boolean',
      createdBy: 'string',
    },
    reportTemplate: {
      id: 'string',
      name: 'string',
      description: 'string',
      type: 'string',
      dataSource: 'string',
      fields: 'string[]',
      filters: 'object',
      groupBy: 'string[]',
      sortBy: 'string',
      calculations: 'object',
      formatting: 'object',
      isCustom: 'boolean',
      isPublic: 'boolean',
      createdBy: 'string',
    },
    reportHistory: {
      id: 'string',
      reportId: 'string',
      templateId: 'string',
      generatedAt: 'Date',
      generatedBy: 'string',
      format: 'string',
      recordCount: 'number',
      fileSize: 'number',
      downloadUrl: 'string',
      emailedTo: 'string[]',
      status: 'success | failed | pending',
    },
    exportJob: {
      id: 'string',
      type: 'string',
      format: 'string',
      status: 'pending | processing | completed | failed',
      progress: 'number',
      recordCount: 'number',
      startedAt: 'Date',
      completedAt: 'Date | null',
      downloadUrl: 'string | null',
      error: 'string | null',
    },
  },
};
